[workspace]
resolver = "2"
members = [
    "core/*",
    "bindings/*"
]

[workspace.dependencies]
ahash = "0.8.11"
async-trait = "0.1.80"
bincode = "2.0.0-rc.3"
bumpalo = "3.16.0"
chrono = "0.4.38"
criterion = "0.5.1"
fastrand = "2.1.0"
futures = "0.3.30"
humantime = "2.1.0"
once_cell = "1.19.0"
petgraph = "0.6.5"
phf = "0.11.2"
regex = "1.10.4"
regex-lite = "0.1.5"
strum = "0.26.2"
strum_macros = "0.26.2"
serde = "1.0.202"
serde_json = "1.0.117"
itertools = "0.13.0"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
json_dotpath = "1.1.0"

anyhow = "1.0.86"
thiserror = "1.0.61"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"